---
dependency:
  name: galaxy
  options:
    requirements-file: collections/requirements.yml
driver:
  name: docker
platforms:
  - name: webapp-full-ubuntu
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: webapp-full-centos
    image: geerlingguy/docker-centos7-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/roles"
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: profile_tasks, timer
  inventory:
    group_vars:
      all:
        environment_name: "Molecule Test"
    host_vars:
      webapp-full-ubuntu:
        ansible_python_interpreter: /usr/bin/python3
      webapp-full-centos:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
